/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2021-01-11 09:19:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.rays.project_3.util.DataUtility;
import in.co.rays.project_3.util.ServletUtility;
import in.co.rays.project_3.ctl.GetMarksheetCtl;
import in.co.rays.project_3.ctl.ORSView;
import in.co.rays.project_3.ctl.LoginCtl;
import in.co.rays.project_3.dto.RoleDTO;
import in.co.rays.project_3.dto.UserDTO;
import in.co.rays.project_3.ctl.ORSView;

public final class GetMarksheetView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1606982788534L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1610356007564L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("in.co.rays.project_3.ctl.GetMarksheetCtl");
    _jspx_imports_classes.add("in.co.rays.project_3.util.ServletUtility");
    _jspx_imports_classes.add("in.co.rays.project_3.ctl.ORSView");
    _jspx_imports_classes.add("in.co.rays.project_3.ctl.LoginCtl");
    _jspx_imports_classes.add("in.co.rays.project_3.dto.RoleDTO");
    _jspx_imports_classes.add("in.co.rays.project_3.util.DataUtility");
    _jspx_imports_classes.add("in.co.rays.project_3.dto.UserDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Get Marksheet View</title>\r\n");
      out.write("<script src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/CheckBox11.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".p1{\r\n");
      out.write("padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hm-gradient {\r\n");
      out.write("\tbackground-image: url('");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/bg1.png');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("#po1 {\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\theight: 25px;\r\n");
      out.write("}\r\n");
      out.write(".footer {\r\n");
      out.write("   position: relative;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   bottom: 0;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   background-color: #484848;\r\n");
      out.write("   color: white;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"hm-gradient\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<title>jQuery UI Datepicker - Display month &amp; year menus</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"/resources/demos/style.css\">\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("  <script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  \r\n");
      out.write("  var d = new Date();\r\n");
      out.write("  function disableSunday(d){\r\n");
      out.write("  \t  var day = d.getDay();\r\n");
      out.write("  \t  if(day==0)\r\n");
      out.write("  \t  {\r\n");
      out.write("  \t   return [false];\r\n");
      out.write("  \t  }else\r\n");
      out.write("  \t  {\r\n");
      out.write("  \t\t  return [true];\r\n");
      out.write("  \t  }\r\n");
      out.write("  }\r\n");
      out.write("  $( function() {\r\n");
      out.write("    $( \"#datepicker\" ).datepicker({\r\n");
      out.write("      changeMonth: true,\r\n");
      out.write("      changeYear: true,\r\n");
      out.write("      yearRange : '1970:2030',\r\n");
      out.write("      dateFormat:'dd/mm/yyyy'\r\n");
      out.write("     \r\n");
      out.write("    });\r\n");
      out.write("  } );\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.6.3/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
 UserDTO userDto=(UserDTO)session.getAttribute("user");
	
		boolean userLoggedIn=userDto!=null;
		
		String welcomeMsg="Hi, ";
		if(userLoggedIn){
			String role=(String)session.getAttribute("role");
			welcomeMsg+=userDto.getFirstName() + "("+role+")";
		}else{
			welcomeMsg+="Guest";
		}
	
	
      out.write("\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\"> \r\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\"><img\r\n");
      out.write("\t\t\tsrc=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/custom.png\" width=\"90px\"\r\n");
      out.write("\t\t\theight=\"40px\"></a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-target=\"#navbarNav\" aria-controls=\"navbarNav\"\r\n");
      out.write("\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link\" href=\"#\"> <span class=\"sr-only\">(current)</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t");

					if (userLoggedIn) {
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (userDto.getRoleId() == RoleDTO.STUDENT) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t<a\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">Marksheet</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"\tfar fa-file-alt\"></i>Marksheet Merit List</a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\">\r\n");
      out.write("\t\t\t\t<a\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">User</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t<li><a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\"><i class=\"fas fa-user-tie\"></i>My Profile</a> \r\n");
      out.write("\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\"><i class=\"\tfar fa-file-alt\"></i>Change Password</a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t");

					} else if (userDto.getRoleId() == RoleDTO.ADMIN) {
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\" style=\"padding-left: 20px;\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">User</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-user-circle\"></i>Add User</a> \r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-user-friends\"></i>User List</a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\" style=\"padding-left: 20px\">\r\n");
      out.write("\t\t\t\t<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">Marksheet</font></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"far fa-file\"></i>Add Marksheet</a> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-paste\"></i>Marksheet List</a> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"\tfar fa-file-alt\"></i>Marksheet Merit List </a> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-paste\"></i>Get Marksheet</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\" style=\"padding-left: 20px\">\r\n");
      out.write("\t\t\t\t<a\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">Role</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa\t fa-user-tie\"></i>Add Role</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i\tclass=\"fas fa-user-friends\"></i>Role List</a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\" style=\"padding-left: 20px\">\r\n");
      out.write("\t\t\t\t<a\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">College</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-university\"></i>Add College</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-building\"></i>College List </a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\" style=\"padding-left: 20px\">\r\n");
      out.write("\t\t\t\t<a\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">Course\r\n");
      out.write("\t\t\t\t\t</font></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-book-open\"></i>Add Course</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(ORSView.COURSE_LIST_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-sort-amount-down\"></i>Course List </a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\" style=\"padding-left: 20px\">\r\n");
      out.write("\t\t\t\t<a\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">Student</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"far fa-user-circle\"></i>Add Student</a> \r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-users\"></i>Student List</a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\" style=\"padding-left: 20px\">\r\n");
      out.write("\t\t\t\t<a\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">Faculty\r\n");
      out.write("\t\t\t\t\t</font></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t  <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t  <i class=\"fas fa-user-tie\"></i>Add Faculty</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><i class=\"\tfas fa-users\"></i>Faculty List</a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\" style=\"padding-left: 20px\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">Time\r\n");
      out.write("\t\t\t\t\t\t\tTable</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"far fa-clock\"></i>Add TimeTable</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-clock\"></i>TimeTable List</a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\" style=\"padding-left: 20px\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <font style=\"color: white;\">Subject</font>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_CTL);
      out.write("\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-calculator\"></i>Add Subject</a> <a\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"");
      out.print(ORSView.SUBJECT_LIST_CTL);
      out.write("\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-sort-amount-down\"></i>Subject List\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"\r\n");
      out.write("\t\t\t\t\tstyle=\"padding-left: 20px; padding-right: 67px\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"><font style=\"color: white;\">");
      out.print(welcomeMsg);
      out.write("\r\n");
      out.write("\t\t\t\t\t</font></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (userLoggedIn) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-sign-out-alt\"></i>Logout </a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\"><i class=\"fas fa-user-tie\"></i>My\r\n");
      out.write("\t\t\t\t\t\t\tProfile</a> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\"> <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-edit\"></i>Change Password\r\n");
      out.write("\t\t\t\t\t\t</a> <a class=\"dropdown-item\" href=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-clone\"></i>Java Doc </a>\r\n");
      out.write("\t\t\t\t\t\t");

							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\"><i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fas fa-sign-in-alt\">Login</i> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"");
      out.print(ORSView.USER_REGISTRATION_CTL);
      out.write("\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-registered\"></i> User Registration</a> ");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<form action=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<h1 style=\"font-size: 40px; padding-top: 24px; color: teal;\">Get Marksheet\r\n");
      out.write("\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<font color=\"red\" size=\"5px\">");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("</font>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t<center>\r\n");
      out.write("\t\t\t\t<font color=\"green\" size=\"5px\">");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("</font>\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t\t\t");
      in.co.rays.project_3.dto.MarksheetDTO dto = null;
      dto = (in.co.rays.project_3.dto.MarksheetDTO) _jspx_page_context.getAttribute("dto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (dto == null){
        dto = new in.co.rays.project_3.dto.MarksheetDTO();
        _jspx_page_context.setAttribute("dto", dto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t  </br>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-5\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\"><input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" name=\"rollNo\" class=\"p1\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(ServletUtility.getParameter("rollNo", request));
      out.write("\">&emsp;</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"btn btn-primary btn-md\" style=\"font-size: 17px\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"operation\" value=\"");
      out.print(GetMarksheetCtl.OP_GO);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t>&emsp;<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage("rollNo", request));
      out.write("</font></div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t");

							if (dto.getRollNo() != null && dto.getRollNo().trim().length() > 0) {
						
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<table  width=\"100%\" style=\"background-color: white;\" border=\"3px\">\r\n");
      out.write("\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\" colspan=\"2\">RollNo</th>\r\n");
      out.write("\t\t\t\t\t<td id=\"po1\" align=\"center\" colspan=\"3\">");
      out.print(DataUtility.getStringData(dto.getRollNo()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\" colspan=\"2\">Name</th>\r\n");
      out.write("\t\t\t\t\t<td id=\"po1\" align=\"center\" colspan=\"3\">");
      out.print(DataUtility.getStringData(dto.getName()));
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr style=\"background-color: #e1b5158c;\">\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\"  >Subject</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\" >Max Marks</th>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\"  >Min Marks</th>\r\n");
      out.write("\t\t\t\t\t<th  id=\"po1\"  colspan=\"2\">Marks Obtain</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\"></td>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\" >Marks</th>\r\n");
      out.write("\t\t\t\t\t<th style=\"color: blue;\" id=\"po1\"  >Grade</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\">Physics</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">100</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">35</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"po1\" align=\"center\">");
      out.print(DataUtility.getStringData(String.valueOf(dto.getPhysics())));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							float physics = dto.getPhysics();
								if (dto.getPhysics() < 35) {
						
      out.write("<span style=\"color: red;\">*</span> ");

 	}
 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (physics >= 90) {
						
      out.write(" <b>A++</b> ");

 	} else if (physics >= 80) {
 
      out.write(" <b>A</b> ");

 	} else if (physics >= 70) {
 
      out.write(" <b>B++</b> ");

 	} else if (physics >= 60) {
 
      out.write(" <b>B</b> ");

 	} else if (physics >= 50) {
 
      out.write(" <b>C++</b> ");

 	} else if (physics >= 40) {
 
      out.write(" <b>C</b> ");

 	} else if (physics >= 35) {
 
      out.write(" <b>D</b> ");

 	} else if (physics >= 0) {
 
      out.write(" <font color=\"red\"><b>F</b></font> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\">Chemistry</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">100</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">35</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"po1\" align=\"center\">");
      out.print(DataUtility.getStringData(String.valueOf(dto.getChemistry())));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							float chemistry = dto.getChemistry();
								if (dto.getChemistry() < 35) {
						
      out.write("<span style=\"color: red;\">*</span> ");

 	}
 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (chemistry >= 90) {
						
      out.write(" <b>A++</b> ");

 	} else if (chemistry >= 80) {
 
      out.write(" <b>A</b> ");

 	} else if (chemistry >= 70) {
 
      out.write(" <b>B++</b> ");

 	} else if (chemistry >= 60) {
 
      out.write(" <b>B</b> ");

 	} else if (chemistry >= 50) {
 
      out.write(" <b>C++</b> ");

 	} else if (chemistry >= 40) {
 
      out.write(" <b>C</b> ");

 	} else if (chemistry >= 35) {
 
      out.write(" <b>D</b> ");

 	} else if (chemistry >= 0) {
 
      out.write(" <font color=\"red\"><b>F</b></font> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\">Maths</th>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">100</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">35</td>\r\n");
      out.write("\t\t\t\t\t<td id=\"po1\" align=\"center\">");
      out.print(DataUtility.getStringData(String.valueOf(dto.getMaths())));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

							float marks = dto.getMaths();
								if (marks <= 35) {
						
      out.write("<span style=\"color: red;\">*</span> ");

 	}
 
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (marks >= 90) {
						
      out.write(" <b>A++</b> ");

 	} else if (marks >= 80) {
 
      out.write(" <b>A</b> ");

 	} else if (marks >= 70) {
 
      out.write(" <b>B++</b> ");

 	} else if (marks >= 60) {
 
      out.write(" <b>B</b> ");

 	} else if (marks >= 50) {
 
      out.write(" <b>C++</b> ");

 	} else if (marks >= 40) {
 
      out.write(" <b>C</b> ");

 	} else if (marks >= 35) {
 
      out.write(" <b>D</b> ");

 	} else if (marks >= 0) {
 
      out.write(" <font color=\"red\"><b>F</b></font> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\" colspan=\"2\">Total</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td id=\"po1\" align=\"center\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t");

							int total = ((dto.getMaths()) + (dto.getPhysics()) + (dto.getChemistry()));
								float percentage = (total * 100) / 300;
						
      out.print(total);
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					if ((dto.getMaths() > 35) && (dto.getPhysics() > 35) && (dto.getChemistry() > 35)) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\" colspan=\"2\">Percentage</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td id=\"po1\" align=\"center\" colspan=\"3\">");
      out.print(percentage);
      out.write("%</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\" align=\"center\" colspan=\"2\"><font color=\"blue\">Grade:</font>\r\n");
      out.write("\t\t\t\t\t\t");

							if (percentage >= 90) {
						
      out.write(" <b>A++</b> ");

 	} else if (percentage >= 80) {
 
      out.write(" <b>A</b> ");

 	} else if (percentage >= 70) {
 
      out.write(" <b>B++</b> ");

 	} else if (percentage >= 60) {
 
      out.write(" <b>B</b> ");

 	} else if (percentage >= 50) {
 
      out.write(" <b>C++</b> ");

 	} else if (percentage >= 40) {
 
      out.write(" <b>C</b> ");

 	} else if (percentage >= 35) {
 
      out.write(" <b>D</b> ");

 	} else if (percentage >= 0) {
 
      out.write(" <font color=\"red\"><b>F</b></font> ");

 	}
 
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t<td id=\"po1\" align=\"center\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t");

							if (percentage >= 35) {
						
      out.write(" <font color=\"green\"><b>PASS</b></font> ");

 	}
 
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th id=\"po1\" align=\"center\" colspan=\"2\"><font color=\"blue\">Final Grade:</font><font\r\n");
      out.write("\t\t\t\t\t\tcolor=\"red\"><b>F</b></font></th>\r\n");
      out.write("\t\t\t\t\t<td id=\"po1\" align=\"center\" colspan=\"3\"><font color=\"red\"><b>FAIL</b></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</form></div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("   position: fixed;\r\n");
      out.write("   left: 0;\r\n");
      out.write("   bottom: 0;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   background-color: #484848;\r\n");
      out.write("   color: white;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("<hr>\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<h5 style=\"color: white; margin-top: -28px;\">&#169; RAYS Technologies</h5></center>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
